using Microsoft.EntityFrameworkCore;
using philcare.Api.Common.Domain;
using philcare.Api.Common.Persistence;
using philcare.Api.Features.Finance.Domain;

namespace philcare.Api.Features.Finance.Expenses.VoidExpense;

public sealed class VoidExpenseHandler(AppDbContext db)
{
    public async Task<Result> HandleAsync(int id, CancellationToken cancellationToken)
    {
        var expense = await db.Expenses
            .Include(e => e.FundingBucket)
            .FirstOrDefaultAsync(e => e.Id == id, cancellationToken);

        if (expense is null)
        {
            return Result.Failure(Error.NotFound("Expenses.NotFound", "Expense not found."));
        }

        if (expense.IsVoided)
        {
            return Result.Failure(Error.Conflict("Expenses.AlreadyVoided", "This expense has already been voided."));
        }

        var distributionLinked = await db.Distributions.AnyAsync(d => d.ExpenseId == expense.Id, cancellationToken);

        if (distributionLinked)
        {
            return Result.Failure(Error.Conflict("Expenses.VoidViaDistribution",
                "This expense was generated by a distribution — void the distribution instead so both records stay in sync."));
        }

        ExpensePosting.Reverse(expense, expense.FundingBucket);

        await db.SaveChangesAsync(cancellationToken);

        return Result.Success();
    }
}
